name: cicd
on:
  push:
    paths:
      - src/**
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Definindo SHA 6 Digitos
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Logando no DockerHUB
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: benyvasc/python-app:${{ env.COMMIT_ID }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      -
        name: Install ArgoCD
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd.svc.cluster.local/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
      -
        name: ArgoCD APP Sync
        shell: bash
        run: |
          argocd login argocd-server.argocd.svc.cluster.local \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync pythin-app
