name: cicd
on:
  push:
    paths:
      - src/**
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Definindo SHA 6 Digitos
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Logando no DockerHUB
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: benyvasc/python-app:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      -
        name: Clone repo
        uses: actions/checkout@v3
      -
        name: Update Values.yaml
        shell: bash
        run: |
          echo ${{ needs.ci.outputs.commit_id }}
          pip3 install yq
          yq -Yi '.image.tag = "${{ needs.ci.outputs.commit_id }}" charts/python-app/values.yaml'
      -
        name: Atualizando Imagem TAG
        uses: EndBug/add-and-commit@v10 # You can change this to use a specific version.
        with:
          author_name: Beny Mota
          author_email: benyvasc@gmail.com
          message: 'Update values.yaml com commit ${{ needs.ci.outputs.commit_id }}'
      -
        name: Install ArgoCD
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd.svc.cluster.local/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
      -
        name: ArgoCD APP Sync
        shell: bash
        run: |
          argocd login argocd-server.argocd.svc.cluster.local \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app